################################################################################
##   ____  ____
##  /   /\/   /
## /___/  \  /    Vendor: Xilinx
## \   \   \/     Version : 2.01
##  \   \         Application : 7Series IBERT v2.02_a Core
##  /   /         Filename : v_rdi_implement.tcl
## /___/   /\     
## \   \  /  \
##  \___\/\___\
##
##
## pa_rdi_implement.tcl script 
## Generated by Xilinx 7Series IBERT v2.02_a Core
##
#-----------------------------------------------------------------------------
# Script to synthesize and implement the RTL provided for the ICON core
#-----------------------------------------------------------------------------
add_files -norecurse {../example_design/example_ibert_v.v}
add_files -norecurse {../example_design/example_ibert_bb_v.v}
add_files -norecurse {../../vivado_ibert.ngc}
set_property target_constrs_file {../example_design/ibert_top.xdc} [current_fileset -constrset]
import_ip -file {chipscope_icon_vivado_1.xco} -name icon_kintex7
generate_target { all } [get_ips icon_kintex7]
add_files -norecurse {../../../icon_kintex7/icon_kintex7.ngc}
set_property top example_ibert [get_filesets sources_1]
read_xdc -cell U_ICON ../../../icon_kintex7/icon_kintex7.constraints/icon_kintex7.xdc
set_property used_in_synthesis false [get_files icon_kintex7.xdc]
set_property used_in_synthesis false [get_files ibert_top.xdc]
reset_run synth_1
launch_runs synth_1
wait_on_run synth_1
reset_run impl_1
launch_runs impl_1 -to_step write_bitstream
wait_on_run impl_1
